#!/bin/bash

## Description: Run Contao console inside the web container
## Usage: contao [flags] [args]
## Example: "ddev contao contao:migrate"
## ProjectTypes: php
## ExecRaw: true

if [ ! -f vendor/bin/contao-console ]; then
  echo 'vendor/bin/contao-console does not exist in your project root directory.'
  echo 'Please verify that you installed Contao in your project directory.'
  exit 1
fi

vendor/bin/contao-console $@
