#!/bin/bash

## Description: Run phpunit command inside the web container
## Usage: phpunit [flags] [args]
## Example: "ddev phpunit --stderr UnitTest.php"
## ProjectTypes: php
## ExecRaw: true

if [ ! -f vendor/bin/phpunit ]; then
  echo 'vendor/bin/phpunit does not exist in your project root directory.'
  echo 'Please verify that you installed PHPUnit in your project directory.'
  exit 1
fi

vendor/bin/phpunit $@
